# All your development & test Gems are belong to us.

# Considering this is a new app e do have a fair amount of Gems all development & test Gems are managed here.
#
#  There are three groupings:
#  - Default Development & Test group
#  - Test group
#  - Development tools & utilities group
#  - Static code analysis, security and linting group

##############################
# Default Development & Test group
##############################
group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  # Debugging functionality for Ruby (https://github.com/ruby/debug)
  gem "debug", platforms: %i[mri mingw x64_mingw]
  # RSpec for Rails (https://github.com/rspec/rspec-rails)
  gem "rspec-rails"
  # the instafailing RSpec progress bar formatter (https://github.com/thekompanee/fuubar)
  gem "fuubar", require: false

  # Code coverage for Ruby (https://github.com/simplecov-ruby/simplecov)
  gem "simplecov", require: false

  # Ruby applications tests profiling tools (http://github.com/test-prof/test-prof)
  gem "test-prof"

  # sampling callstack-profiler for ruby 2.2+ (http://github.com/tmm1/stackprof)
  gem "stackprof", ">= 0.2.9", require: false

  # Record the operation of a Ruby program, using the AppLand 'AppMap' format. (https://github.com/applandinc/appmap-ruby)
  gem "appmap"
end

##############################
# Test Group
##############################
group :test do
  # Capybara aims to simplify the process of integration testing Rack applications, such as Rails, Sinatra or Merb (https://github.com/teamcapybara/capybara)
  gem "capybara"
  # Headless Chrome driver for Capybara (https://github.com/rubycdp/cuprite)
  gem "cuprite"
end

##############################
# Development tools & utilities group
##############################
group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  # A debugging tool for your Ruby on Rails applications. (https://github.com/rails/web-console)
  gem "web-console"
  gem "rack-mini-profiler"
  # Preview mail in browser instead of sending. (https://github.com/ryanb/letter_opener)
  gem "letter_opener"
  # Automatically reload Hotwire Turbo when app files are modified. (https://github.com/kirillplatonov/hotwire-livereload)
  gem "hotwire-livereload", "~> 1.1"
  # Pretty print Ruby objects with proper indentation and colors (https://github.com/awesome-print/awesome_print)
  gem "awesome_print", "~> 1.9"
  # Colorize printed text on ANSI terminals (https://github.com/sickill/rainbow)
  gem "rainbow"
end

##############################
#  Static code analysis, security and linting group.
##############################
group :development do
  # Alias for the standard gem, which has a standardrb binary (https://github.com/testdouble/standardrb)
  gem "standardrb"
  # Add comments to your Gemfile with each dependency's description. (https://github.com/ivantsepp/annotate_gem)
  gem "annotate_gem", require: false
  # Annotates Rails Models, routes, fixtures, and others based on the database schema. (https://github.com/ctran/annotate_models)
  gem "annotate"
  # Code smell detector for Ruby (https://github.com/troessner/reek)
  gem "reek", require: false
  # Git hook manager (https://github.com/sds/overcommit)
  gem "overcommit", require: false
  # Patch-level verification for Bundler (https://github.com/rubysec/bundler-audit#readme)
  gem "bundler-audit", require: false
  # Security vulnerability scanner for Ruby on Rails. (https://brakemanscanner.org)
  gem "brakeman", require: false
  # A Rake task that helps you find the dead routes and actions for your Rails 3 app (https://github.com/amatsuda/traceroute)
  gem "traceroute"
  # a code metric tool for rails codes. (http://rails-bestpractices.com)
  gem "rails_best_practices"
  # ERB lint tool (https://github.com/Shopify/erb-lint)
  gem "erb_lint", require: false
  # YAML lint checker
  gem "yamllint"
end
